// Mocks generated by Mockito 5.4.6 from annotations
// in hotdeal_with_hono/test/src/presentation/viewmodel/sign_up_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hotdeal_with_hono/src/application/usecase/check_nickname_usecase.dart'
    as _i4;
import 'package:hotdeal_with_hono/src/application/usecase/sign_up_usecase.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUseCase extends _i1.Mock implements _i2.SignUpUseCase {
  MockSignUpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({
    required String? email,
    required String? password,
    required String? passwordCheck,
    required String? nickname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #password: password,
              #passwordCheck: passwordCheck,
              #nickname: nickname,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CheckNicknameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckNicknameUseCase extends _i1.Mock
    implements _i4.CheckNicknameUseCase {
  MockCheckNicknameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> call(String? nickname) =>
      (super.noSuchMethod(
            Invocation.method(#call, [nickname]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
