// Mocks generated by Mockito 5.4.6 from annotations
// in hotdeal_tuum/test/domain/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:hotdeal_tuum/data/api/services/auth_api.dart' as _i4;
import 'package:hotdeal_tuum/data/services/token_storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenStorageService_1 extends _i1.SmartFake
    implements _i3.TokenStorageService {
  _FakeTokenStorageService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i4.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i3.TokenStorageService get tokenStorageService =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStorageService),
            returnValue: _FakeTokenStorageService_1(
              this,
              Invocation.getter(#tokenStorageService),
            ),
          )
          as _i3.TokenStorageService);

  @override
  _i5.Future<void> login({
    required String? email,
    required String? password,
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #email: email,
              #password: password,
              #rememberMe: rememberMe,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
