// Mocks generated by Mockito 5.4.6 from annotations
// in hotdeal_with_hono/test/src/application/usecase/check_nickname_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hotdeal_with_hono/src/domain/model/token.dart' as _i2;
import 'package:hotdeal_with_hono/src/domain/repository/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeToken_0 extends _i1.SmartFake implements _i2.Token {
  _FakeToken_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Token> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<_i2.Token>.value(
              _FakeToken_0(this, Invocation.method(#login, [email, password])),
            ),
          )
          as _i4.Future<_i2.Token>);

  @override
  _i4.Future<_i2.Token> signUp({
    required String? email,
    required String? password,
    required String? nickname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #nickname: nickname,
            }),
            returnValue: _i4.Future<_i2.Token>.value(
              _FakeToken_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #nickname: nickname,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Token>);

  @override
  _i4.Future<bool> checkNicknameAvailability(String? nickname) =>
      (super.noSuchMethod(
            Invocation.method(#checkNicknameAvailability, [nickname]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkEmailAvailability(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailAvailability, [email]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
